<?php

namespace Charlotte\StaffBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Rolesdescription
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rolesdescription extends EntityRepository
{
    /**
     * Retourne un tableau des descriptions des rôles avec le rôle pour clef
     * @return results
     */
    public function findAllDescription()
    {
        $rolesdescription = array();
        foreach ($this->findAll() as $value) {
            $rolesdescription[$value->getName()] = $value->getDescription() ? $value->getDescription() : $value->getName();
         }

        return $rolesdescription;
    }
}
