<?php

namespace Charlotte\StaffBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Team
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Team extends EntityRepository
{
    /**
     * Retourne un groupe de rôle en fonction d'un rôle
     * @param string $role
     *
     * @return array
     */
    public function findByRole($role)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('t')
            ->from($this->_entityName, 't')
            ->where('t.roles LIKE :roles')
            ->setParameter('roles', '%'.$role.'%');

        return $qb->getQuery()->getResult();
    }

}
